server:
  port: 7001

spring:
  application:
    name: config-server
  # Git 仓库相关信息
  # 配置信息的 URL 与配置文件的映射关系
  # /{application}/{profile}/[label]
  # /{application}-{profile}.yml
  # /label/{application}-{profile}.yml
  # 例如：localhost:7001/config/test/config-label-test
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lxiaocode/spring-cloud-config-repo         # Git 仓库位置
          search-paths: spring-cloud-study/spring_cloud_config/config_repo  # 仓库路径下的相对搜索位置
          username: lxiaocode@qq.com    # Git 仓库用户名
          password: lxiaocode@123       # Git 仓库密码

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/