spring:
  application:
    name: ribbon-consumer
  # 重试机制配置
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启重试机制

hello-service:
  ribbon:
    ConnectTimeout: 250             # 请求连接的超时时间
    ReadTimeout: 1000               # 请求处理的超时时间
    OkToRetryOnAllOperations: true  # 对所有操作都进行重试
    MaxAutoRetriesNextServer: 2     # 切换实例的重试次数
    MaxAutoRetries: 1               # 当前实例的重试次数

server:
  port: 4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/

# 参数配置
# 全局配置 以及 指定客户端配置

# 全局配置 ribbon.<key>=<value>
# 指定客户端配置 <client>.ribbon.<key>=<value>

# Ribbon 参数可以参考 com.netflix.client.config.CommonClientConfigKey
